# Generated by Django 5.0.6 on 2024-06-18 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
